# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: add8e8e9c7ecf6da8af1eadd92b5009a7048d9ead214d2b45026ba4747afa0efd8636e8da0a3633d5e9e9cbe799642f77a80312a66c0056acf10b8ec2d5a6299

test:
  secret_key_base: 8d6ab54ab755e18b0637c824c62ef29fda7d5c2a0f2f56c5f38454ef2c91d3309041e824adace51e51ef330b276530346a8d8d86e88e19ed24d2cb430de66329

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
